-- Case 01 Survey Site / Supabase schema
-- 在 Supabase SQL Editor 執行一次即可。

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  respondent_id uuid not null,
  source text not null default 'unknown',
  campaign text not null default '',
  answers jsonb not null,
  started_at timestamptz,
  completed_at timestamptz not null default now(),
  duration_seconds integer,
  user_agent text,
  referrer text,
  created_at timestamptz not null default now()
);

create index if not exists survey_responses_source_idx on public.survey_responses(source);
create index if not exists survey_responses_completed_at_idx on public.survey_responses(completed_at);
create index if not exists survey_responses_answers_gin_idx on public.survey_responses using gin(answers);

create table if not exists public.survey_contacts (
  id bigint generated by default as identity primary key,
  channel text not null,
  contact text not null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.survey_responses enable row level security;
alter table public.survey_contacts enable row level security;

drop policy if exists "anon_insert_survey_responses" on public.survey_responses;
create policy "anon_insert_survey_responses"
on public.survey_responses
for insert
to anon
with check (true);

drop policy if exists "anon_insert_survey_contacts" on public.survey_contacts;
create policy "anon_insert_survey_contacts"
on public.survey_contacts
for insert
to anon
with check (true);
